version: "3"
services:
  prism:
    build: .
    ports:
      - "3034:3034"
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yml
    volumes:
      - ./openapi.yml:/openapi/openapi.yml
    ports:
      - "3035:8080"
  redoc:
    image: redocly/redoc
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi/openapi.yml:cached
    environment:
      - SPEC_URL=/openapi/openapi.yml
    ports:
      - "3036:80"
