openapi: 3.0.0
info:
  title: Recustomer API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://{your_server}/{your_endpoint}
paths:
  /{your_endpoint}:
    post:
      operationId: shipping_status_webhook
      summary: Shipping Status Webhook
      description: real-time notification for shipments tracking , providing updates on package status during transit
      tags:
        - "Webhook"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - tracking_number
                - latest_tracking_status
                - delivery_company
              properties:
                tracking_number:
                  type: string
                  description: tracking number
                estimated_delivery_date:
                  type: string
                  description: order id
                latest_tracking_status:
                  type: string
                  enum:
                    - 荷物受付け
                    - 配送中
                    - コンビニ受取可能
                    - お届け完了
                    - 不在通知
                    - 配送トラブル発生
                    - 保管期限超過によるお届け失敗
                  description: latest tracking status
                delivery_company:
                  type: string
                  description: delivery company
                logistics_centers:
                  type: array
                  items:
                    properties:
                      center:
                        type: object
                        properties:
                          center_name: 
                            type: string
                            description: logistics center name
                          center_address:
                            type: string
                            description: logistics center address
                          updated_at:
                            type: string
                            description: arrived at the center
                          status:
                            type: string
                            description: status name at the center
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:      
                  results:
                    type: string