openapi: 3.0.0
info:
  title: Recustomer API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://{your_server}/{your_endpoint}
paths:
  /{your_endpoint}:
    post:
      operationId: delivery_status_webhook
      summary: Delivery Status Webhook
      description: real-time notification for delivery tracking , providing updates on package status during transit
      tags:
        - "Webhook"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - tracking_number
                - latest_tracking_status
                - delivery_company
              properties:
                tracking_number:
                  type: string
                  description: 追跡番号
                estimated_delivery_date:
                  type: string
                  description: 配送予定日
                latest_tracking_status:
                  type: string
                  enum:
                    - 荷物受付け
                    - 配送中
                    - コンビニ受取可能
                    - お届け完了
                    - 不在通知
                    - 配送トラブル発生
                    - 保管期限超過によるお届け失敗
                  description: 最新の配送ステータス
                delivery_company:
                  type: string
                  description: 配送会社名
                checkpoints:
                  type: array
                  items:
                    properties:
                      checkpoint_name:
                        type: string
                        description: 営業所名
                      checkpoint_address:
                        type: string
                        description: 営業所住所
                      updated_at:
                        type: string
                        description: 到着日時
                      delivery_status:
                        title: Delivery Status
                        type: string
                        description: ステータス名
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: string

  /api/v1/tracking/order:
    get:
      operationId: getOrderByTrackingNumber
      summary: Get Order By Tracking Number
      parameters:
        - in: query
          name: tracking_number
          schema:
            title: Tracking Number
            description: 配送追跡番号
            type: string
          required: true
          description: 配送追跡番号
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
      description: 注文を取得する
      tags:
        - Tracking

  /api/v1/tracking/order/{external_order_id}:
    get:
      operationId: getOrderByOrderId
      summary: Get Order By Order Id
      parameters:
        - in: path
          name: external_order_id
          schema:
            title: External Order Id
            description: 外部システムにある注文のID
            type: string
          required: true
          description: 外部システムにある注文のID

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
      description: 注文を取得する
      tags:
        - Tracking

components:
  schemas:
    OrderResponse:
      title: OrderResponse
      type: object
      properties:
        external_order_id:
          title: External Order Id
          description: 外部システムにある注文のID
          example: 12345
          type: string
        order_number:
          title: Order Number
          description: 注文番号
          example: '#1010'
          type: string
        deliveries:
          title: Delivery
          description: 配送追跡情報
          type: array
          items:
            $ref: '#/components/schemas/TrackingInfoResponse'
      required:
        - external_order_id
        - order_number
        - deliveries

    TrackingInfoResponse:
      title: TrackingInfoResponse
      type: object
      properties:
        estimated_delivery_date:
          title: Estimated Delivery Date
          description: 到着予定日
          example: 10月20日
          type: string
        latest_tracking_status:
          type: string
          enum:
            - 荷物受付け
            - 配送中
            - コンビニ受取可能
            - お届け完了
            - 不在通知
            - 配送トラブル発生
            - 保管期限超過によるお届け失敗
          description: 最新の配送ステータス
        tracking_number:
          title: Tracking Number
          description: 追跡番号
          example: '12345678910'
          type: string
        delivery_company:
          title: Delivery Company
          description: 配送会社情報
          allOf:
            - $ref: '#/components/schemas/MasterDeliveryCompany'
        checkpoints:
          title: Checkpoints
          description: 追跡情報
          type: array
          items:
            $ref: '#/components/schemas/PortalTrackingStatusResponse'
        order_created_at:
          title: Order Created At
          description: 注文日時
          type: string
          format: date-time
        line_items:
          title: Line Items
          description: 配送ごとの商品情報(中身は仮置き)
          type: array
          items:
            $ref: '#/components/schemas/OrderLineItem'
      required:
        - delivery_company
        - checkpoints
        - order_created_at
        - line_items

    MasterDeliveryCompany:
      title: MasterDeliveryCompany
      type: object
      properties:
        name:
          title: Name
          description: 配送会社名
          enum:
            - sagawa
            - yamato
            - japan post
          type: string
      required:
        - name

    PortalTrackingStatusResponse:
      title: PortalTrackingStatusResponse
      type: object
      properties:
        delivery_status:
          title: Delivery Status
          description: 配送ステータス
          example: 荷物受付
          type: string
        checkpoint_name:
          type: string
          description: 営業所名
          example: ~営業所
        checkpoint_address:
          type: string
          description: 営業所
          example: tokyo~
        updated_at:
          title: Updated At
          example: '2023-10-20 12:00:00'
          type: string
          format: date-time

    OrderLineItem:
      title: OrderLineItem
      type: object
      properties:
        external_item_id:
          title: External Item Id
          description: 外部システムにある商品のID
          type: string
        sku:
          title: Sku
          description: SKU
          type: string
        product_name:
          title: Product Name
          description: 商品名
          type: string
        image_link:
          title: Image Link
          description: 商品画像
          type: string
      required:
        - external_item_id
        - sku
        - product_name
        - image_link

    TrackingInfoSearchByName:
      title: TrackingInfoSearchByName
      type: object
      properties:
        external_order_id:
          title: External Order Id
          description: 外部システムにある注文のID
          type: string
        tracking_number:
          title: Tracking Number
          description: 配送追跡番号
          type: string
